### ISSUE TITLE
How to easily specify a equal effort allocation design?

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/dssd#54]
`dssd` produces an allocation of effort that is equal (by covered area percentage) across strata in a default manner. 
![image](https://user-images.githubusercontent.com/330744/76965715-af57f780-691c-11ea-99a8-c9fe66e870fd.png)

I am suspicious that users are incorrectly assuming that setting the argument `line.length` to a single value will produce an equal effort design.

What happens when a vector is provided to `line.length`?

How does `line.length` and `effort.allocation` interact?

None of example code in documentation shows the existence of the `effort.allocation` argument.

**Comment by LHMarshall** [comment]
_Setting line.length to a single value should produce an equal effort design... assuming the user hasn't over ridden it using spacing._

What happens when a vector is provided to line.length? _dssd tries to create the requested line length in each stratum individually._

How does line.length and effort.allocation interact? _Line length overrides effort allocation._

None of example code in documentation shows the existence of the effort.allocation argument. _No, but I cannot put every combination in the example code. I could however expand the explanation in the Details section of the help file._

I also have further description currently in the strata example vignette

![Screenshot 2020-11-17 at 01 02 27](https://user-images.githubusercontent.com/1295691/99327416-d2eb8d00-2871-11eb-8cc1-fe12eb5ffbd7.png)

![Screenshot 2020-11-17 at 01 02 17](https://user-images.githubusercontent.com/1295691/99327431-dc74f500-2871-11eb-999e-07fd73d8a2d5.png)

**Comment by LHMarshall** [comment]
Hmm I could also put in warnings to tell users which arguments are being ignored and also tidy up the design object to remove those arguments so the design summary accurately reflects the design. For example the following should have only retained the spacing argument.

```
> design <- make.design(transect.type = "line",
+                       design = "systematic",
+                       samplers = 10,
+                       line.length = 100)
> design

   Strata region:
   _______________
Design:  systematically spaced transects
Spacing:  NA
Number of samplers:  10  (shared across strata)
Line length:  100  (shared across strata)
Design angle:  0
Edge protocol:  minus

Strata areas:  1e+06
```

**Comment by LHMarshall** [comment]
A lot of work has been done on this prior to CRAN release 0.3.0 I will create a new issue to generate another vignette with more effort allocation examples.
